import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthProvider } from "@/components/AuthProvider";
import { PayPalProvider } from "@/components/PayPalProvider";
import { GenerationStatusToast } from "@/components/GenerationStatusToast";
import { Toaster } from "sonner";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <div className="min-h-screen bg-background text-foreground flex flex-col">
          <AuthProvider>
            <PayPalProvider>
              {children}
            </PayPalProvider>
            <GenerationStatusToast />
          </AuthProvider>
          <Toaster 
            position="top-right" 
            richColors 
            closeButton
            theme="dark"
          />
        </div>
      </body>
    </html>
  );
}
